services:
  discoveryservice:
    image: registry
    #restart: always
    ports:
      - "8010:8010"
    networks:
      - photoappapi-network

  api-gateway:
    image: apigateway
    #restart: always
    ports:
      - "8082:8082"
    networks:
      - photoappapi-network
    depends_on:
      - discoveryservice
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discoveryservice:8010/eureka

  PhotoAppApiConfigServer:
    image: configserver
    #restart: always
    ports:
      - "8012:8012"
    networks:
      - photoappapi-network
    depends_on:
      - mor-mysql
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mor-mysql:3306/photo_app
      SPRING_DATASOURCE_USERNAME: mohit
      SPRING_DATASOURCE_PASSWORD: 12345

  users-ws:
    image: users
    #restart: always
    ports:
      - "8001:8001"
    networks:
      - photoappapi-network
    depends_on:
      - discoveryservice
      - PhotoAppApiConfigServer
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discoveryservice:8010/eureka
      SPRING.CONFIG.IMPORT: optional:configserver:http://PhotoAppApiConfigServer:8012
      SPRING_DATASOURCE_URL: jdbc:mysql://mor-mysql:3306/photo_app
      SPRING_DATASOURCE_USERNAME: mohit
      SPRING_DATASOURCE_PASSWORD: 12345

  albums-ws:
    image: albums
    #restart: always
    ports:
      - "8006:8006"
    networks:
      - photoappapi-network
    depends_on:
      - discoveryservice
      - PhotoAppApiConfigServer
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://discoveryservice:8010/eureka
      SPRING.CONFIG.IMPORT: optional:configserver:http://PhotoAppApiConfigServer:8012
      SPRING_DATASOURCE_URL: jdbc:mysql://mor-mysql:3306/photo_app
      SPRING_DATASOURCE_USERNAME: mohit
      SPRING_DATASOURCE_PASSWORD: 12345

  mor-mysql:
    image: mysql:latest
    ports:
      - "8011:3306"
    #restart: always
    environment:
      MYSQL_DATABASE: photo_app
      MYSQL_USER: mohit
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - photoappapi-network

networks:
  photoappapi-network: